### ISSUE TITLE
Détermination de la première primitive 

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#1]
Dans l'exemple https://github.com/0Yassine0/COTS.jl/blob/ecf06913a04366f415d3fce6add10f6ee8c0a5b3/TestProblems/testChain.ipynb#L414 je n'ai pas réussi à déterminer les premières primitives avec la règle des trapèzes pour la modélisation en JuMP.

Pour les afficher avec les résultats de plots venant de OptimalControl.jl il est important qu'ils soient de même taille. C'est pour ça j'ai dupliqué les 2es primitives pour pouvoir afficher la comparaison.

**Comment by ocots** [comment]
Merci pour l'information. A voir pourquoi il y a ce décalage sur les courbes.

**Comment by ocots** [comment]
Notre interpolation + extrapolation : https://github.com/control-toolbox/CTBase.jl/blob/9fab5c59df003776f6f15a9453f9e949aa51dfb2/src/utils.jl#L151

On interpole sur les N-1 premiers points : https://github.com/control-toolbox/CTDirect.jl/blob/ffdabc9ec81bc09589b812906a2670cce14c6d2f/src/solution.jl#L83

**Comment by ocots** [comment]
@0Yassine0 On en est où pour cette issue ?

**Comment by 0Yassine0** [comment]
@ocots J'ai créé une fonction pour faire l'interpolation comme dans `OC` (voir [utils](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/utils.jl) ).
On peut fermer cette issue.
