### ISSUE TITLE
Resolving the Space Shuttle Reentry Problem with OptimalControl

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#10]
The space-shuttle reentry problem, inspired from a JuMP [tutorial](https://jump.dev/JuMP.jl/stable/tutorials/nonlinear/space_shuttle_reentry_trajectory/), is modeled in this [file](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/JuMP/space_Shuttle_JMP.jl). The problem is solved in this [notebook](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/testSpaceShuttleJMP.ipynb), and our goal is to compare its results with those obtained using `OptimalControl.jl`.

However, the problem remains unsolved using `OptimalControl.jl`. The latest results we obtained are available here [testSpaceShuttleOC](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/testSpaceShuttleOC.ipynb). 

The problem diverges, and the solver does not find a solution after 3000 iterations ( in the notebook we set `max_iter=500` for better display of results).

**Comment by ocots** [comment]
Ping @jbcaillau, @PierreMartinon and @joseph-gergaud.

**Comment by 0Yassine0** [comment]
@joseph-gergaud J'ai update le problème avec les modifications dont on a parlé hier pour [space_Shuttle_JMP](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/JuMP/space_Shuttle_JMP.jl) et [space_Shuttle_OC](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/OptimalControl/space_Shuttle_OC.jl) . Et j'ai rajouté à la fin du [testSpaceShuttleOC](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/testSpaceShuttleOC.ipynb) l'affichage des deux Initial guess pour les comparer.

**Comment by ocots** [comment]
@joseph-gergaud @0Yassine0 Des nouvelles de cette application ?

**Comment by ocots** [comment]
@0Yassine0 Any news?
