### ISSUE TITLE
Dérivée de contrôle dans Fatrop 

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#11]
@frapac @ocots. 
Dans [Fatrop benchmarks](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks), les deux problemes [quadcopter](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks/-/tree/T1_problems/quadcopter?ref_type=heads) et [truck trailer](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks/-/tree/T1_problems/truck_trailer?ref_type=heads) ont des conditions sur la dérivée de contrôle, comme [ici](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks/-/blob/T1_problems/truck_trailer/dynamics.py?ref_type=heads#L62) par exemple. Pour `JuMP`, j'ai essayé d'utiliser la définition de la dérivée discrète d'une fonction 
`u_dot[j=1:nh], (u[j] - u[j-1]) / step` : [lien](https://github.com/0Yassine0/COTS.jl/blob/45f2b445d292ecf99d4734bb599961b30864d9c4/Problems/JuMP/quadrotor_JMP.jl#L40)
Mais je ne suis pas sur si cela fonctionne bien vu que les deux problèmes convergent vers des points qui ne respectent pas toutes les contraintes. Et pour `OC`, je ne sais pas comment intégrer cette contrainte ([Ref](https://github.com/0Yassine0/COTS.jl/blob/45f2b445d292ecf99d4734bb599961b30864d9c4/Problems/OptimalControl/truck_trailer_OC.jl#L91))

**Comment by ocots** [comment]
C'est bizarre toutes ces contraintes. Il va falloir qu'on creuse un peu...

**Comment by 0Yassine0** [comment]
J'ai modifié le problème du [quadcopter](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks/-/tree/T1_problems/quadcopter?ref_type=heads) avec `OptimalControl` pour l'adapter à ce qu'on a discuté hier pour les dérivées.
J'ai affiché les résultats dans le fichier  [testQuadrotorP2P](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/testQuadrotorP2P.ipynb).
Étonnamment les résultats sont proches, les trajectoires ont l'air d'etre similaire. Mais, le seul problème c'est le temps finale `tf`!`OptimalControl` trouve une valeur plus grande que `JuMP`.
Modélisation en Jump : [lien](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/JuMP/quadrotorP2P_JMP.jl)
Modélisation en OC : [lien](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/OptimalControl/quadrotorP2P_OC.jl)

**Comment by ocots** [comment]
Juste une remarque en attendant. Je vois que tu as essayé de faire des animations. Tu peux faire des gif ou mp4. Deux exemples : 

- https://gitlab.irit.fr/toc/etu-n7/controle-optimal/-/blob/master/tp/ode.ipynb : voir vers la fin sur l'attracteur de Lorenz
- https://gitlab.irit.fr/toc/etu-n7/controle-optimal/-/blob/master/tp/space.jl?ref_type=heads#L308

**Comment by ocots** [comment]
Autre exemple : https://github.com/control-toolbox/kepler
