### ISSUE TITLE
Conditions initiales et finales sur le controle 

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#12]
@frapac @ocots. 
Dans [Fatrop benchmarks](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks), le problème [quadcopter](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks/-/tree/T1_problems/quadcopter?ref_type=heads) a des conditions initiales et finales sur le contrôle, comme [ici](https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_benchmarks/-/blob/T1_problems/quadcopter/p2p/problem_specification.py?ref_type=heads#L31). Et pour `OptimalControl`, je pense qu'on ne peut pas faire ça : `bad constraint declaration`.

**Comment by ocots** [comment]
En fait le contrôle peut changer instantanément et tu te souviens que par intégration, on ne distingue pas deux fonctions égales presque partout, cf. cours de mesure et intégration de première année. Donc changer la valeur du contrôle sur un ensemble de mesure nulle ne change pas la trajectoire. Du coup, en principe ceci ne sert à rien. Je vais voir plus précisément le problème.

**Comment by 0Yassine0** [comment]
Oui, merci monsieur pour le rappel.
J'ai réussi à trouver une solution avec `JuMP` pour l'instant.
J'ai aussi vu ce [papier](https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=2324&context=facpub) que je trouve intéressant.

**Comment by frapac** [comment]
Pour le problème de quadrotor, il est décrit originellement dans [ce papier](https://www.flyingmachinearena.ethz.ch/wp-content/publications/2011/hehn_dandrea_flying_inverted_pendulum.pdf). 

Le modèle mathématique est aussi présenté [ici](https://arxiv.org/pdf/2005.06674), Section IV.A.
