### ISSUE TITLE
Solving with OptimalControl

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#13]
@frapac @ocots @jbcaillau @PierreMartinon
J'ai re-initialisé l'environnement de Julia et j'ai installé la nouvelle version de `OptimalControl`.
Mais j'ai quelques soucis en exécutant avec `OC`. 
J'ai eu cet erreur : 
`MethodError: no method matching init(::CTBase.OptimalControlModel{Autonomous, Fixed}, ::Symbol, ::Symbol; display::Bool, init::Tuple{})`
J'ai créé ce [notebook](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/Error.ipynb) pour un problème facile.

**Comment by PierreMartinon** [comment]
Bonjour Yassine !
Oui, il faut maintenant ajouter la ligne
```
using NLPModelsIpopt
```
avant de pouvoir faire un *solve*

On essaiera d'afficher un message plus clair.
Pierre
