### ISSUE TITLE
Derivative of the Truck Trailer Problem

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#15]
@frapac @ocots @joseph-gergaud.
J'ai une petite update pour le problème de *Truck Trailer* qui a des conditions sur la dérivée de contrôle ( #11 ).
Ce qu'on a discuté c'est de considérer le contrôle comme variable d'état et de contrôler sa dérivée pour pouvoir appliquer ces contraintes. Ce qui ne donne pas des résultats pour l'instant.
Avec `JuMP`, j'ai utilisé la définition de la dérivée discrète d'une fonction, cela fonctionne bien.
Pour faire une comparaison entre les deux packages, j'ai transformé le modèle `JuMP` de la même façon que `OC`, càd sans utiliser la définition de la dérivée et ce modèle converge vers un point qui ne respecte pas les contraintes.
Donc je pense que la modélisation `OC` de cette manière ne va pas être résolue.

Liens:
* Modèle `JuMP` avec la définition de la dérivée : [truck_trailer_JMP](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/JuMP/truck_trailer_JMP.jl)
* Modèle `OC` : [truck_trailer_OC](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/OptimalControl/truck_trailer_OC.jl)
* Modèle `JuMP` analogue à OC : [truck_trailer_JMP_FAIL](https://github.com/0Yassine0/COTS.jl/blob/main/Problems/JuMP/truck_trailer_JMP_FAIL.jl)
* Notebook d'exécution : [testTruckTrailer](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/testTruckTrailer.ipynb)

**Comment by ocots** [comment]
Merci pour le retour.

**Comment by ocots** [comment]
@0Yassine0 Can we close?
