### ISSUE TITLE
Benchmark of Goddard Rocket Problem

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#2]

**Comment by 0Yassine0** [comment]
Bonjour,
J’ai rencontré quelques difficultés dans la recherche du nombre de nonzeroes dans le Jacobian et le Hessian.
* Pour le modèle JuMP linéaire ( qui utilise `@contraintes` et non pas `@NLcontraintes`), il ne propose pas des fonctions de récupération des données nécessaires pour la Jacobienne des contraintes.
J'étais obligé de passer d’une manière détournée en le convertissant en un modèle non linéaire et j'aimerai bien savoir ce que vous pensiez.
```
nlp = MOI.Nonlinear.Model()
for (F, S) in list_of_constraint_types(model)
   if F <: VariableRef
       continue
   end
   for ci in all_constraints(model, F, S)
       object = constraint_object(ci)
       MOI.Nonlinear.add_constraint(nlp, object.func, object.set)
   end
end
MOI.Nonlinear.set_objective(nlp, objective_function(model))
evaluator = MOI.Nonlinear.Evaluator(
   nlp,
   MOI.Nonlinear.SparseReverseMode(),
   index.(all_variables(model)),
)
MOI.initialize(evaluator, MOI.features_available(evaluator))
nnz_hess = length(MOI.hessian_lagrangian_structure(evaluator))
nnz_jac = length(MOI.jacobian_structure(evaluator))
```
* Pour le modèle OptimalControl, la solution et le modèle ne stocke pas ces données. J’ai trouvé que dans le package CTDirectSooting il y a un bout de code qui aide à chercher la matrice jacobienne mais je suppose qu’il y a une façon plus directe pour renvoyer le nombre des nonzeros avec la solution.

**Comment by ocots** [comment]
Dans `OptimalControl`, on utilise [ADNLPModels](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/) qui implémente l'API de [NLPModel](https://github.com/JuliaSmoothOptimizers/NLPModels.jl). A voir si l'on peut récupérer les infos. Ne pas hésiter à demander à @amontoison.

**Comment by ocots** [comment]
Sur la page de [NLPModel](https://github.com/JuliaSmoothOptimizers/NLPModels.jl?tab=readme-ov-file#attributes), on a : 

nnzo | Int | number of nonzeros in the gradient
-- | -- | --
nnzj | Int | number of nonzeros in the sparse Jacobian
nnzh | Int | number of nonzeros in the sparse Hessian

**Comment by amontoison** [comment]
@0Yassine0 Je te conseille `NLPModelsJuMP.jl`. Il permet de récupérer les différents types de contraintes / objectifs pour récupérer les informations du modèle JuMP avec la même API que NLPModels.jl.

**Comment by ocots** [comment]
@0Yassine0 On en est où pour cette issue ?

**Comment by 0Yassine0** [comment]
Pour la récupération des données je pense qu'on est bien, j'ai réussi à avoir tout ce que je veux comparer pour les deux modèles.
On peut fermer cette issue.
