### ISSUE TITLE
Benchmark the time spent in evaluating the model (Task #2) 

### ISSUE THREAD

**Issue by frapac** [0Yassine0/COTS.jl#20]
We should use the NLPModels.jl's interface to measure the time spent in each callback. 

E.g., for a JuMP model, we can convert it as a NLPModels.jl using NLPModelsJuMP.jl and do
```julia
using NLPModels, using NLPModelsJuMP
model = # ... generate JuMP model 
nlp = MathOptNLPModel(model)

n, m = get_nvar(nlp), get_ncon(nlp)
x0 = get_x0(nlp)
y0 = get_y0(nlp)
t_obj = @elapsed NLPModels.obj(nlp, x0)

g = zeros(n)
t_grad = @elapsed NLPModels.grad!(nlp, x0, g)

cons = zeros(m)
t_cons = @elapsed NLPModels.cons!(nlp, x0, cons)

nnzj = get_nnzj(nlp)
jac = zeros(nnzj)
t_jac = @elapsed NLPModels.jac_coord!(nlp, x0, jac) 

nnzh = get_nnzh(nlp)
hess = zeros(nnzh)
t_hess = @elapsed NLPModels.hess_coord!(nlp, x0, y0, hess) 

```
We can also replace `@elapsed` with the macro `@btime` from BenchmarkTools.jl for more accurate measurement.

**Comment by frapac** [comment]
@0Yassine0 For OC, we can generate the NLPModels directly with: 

```julia
nh = 100
ocp = ... # generate your problem with OC.jl
docp = OptimalControl.direct_transcription(ocp; grid_size=nh)
nlp = docp.nlp 
```

**Comment by frapac** [comment]
Ok, that looks good to me. 
A few remarks: 
- can you make sure you are benchmarking the precompiled callbacks? This should be handled automatically if we use the macro `@btime` in BenchmarkTools.jl. Another option is to call `callback_nlp` twice. 
- can you specify the time in milliseconds? 
- can you get the number of colors used by the automatic differentiation backend, both for JuMP and for OC?

**Comment by 0Yassine0** [comment]
Yes, it's precompiled. I run it when calling the module of `Benchmark` [here](https://github.com/0Yassine0/COTS.jl/blob/7d04a6b5b5fb093784477f7ba458ac6dbd104a36/Benchmark/Benchmark.jl#L41). I haven't used `@btime` because it just prints the information it's easier to get the Float results with `@timed`.
I'll add the results you asked for.

**Comment by frapac** [comment]
Right, you could replace the macro `@btime` with `@belapsed` to get the computation time. I would recommend using BenchmarkTools.jl, to avoid using our own workaround to precompile the functions before the benchmark.

**Comment by 0Yassine0** [comment]
> Right, you could replace the macro `@btime` with `@belapsed` to get the computation time. I would recommend using BenchmarkTools.jl, to avoid using our own workaround to precompile the functions before the benchmark.

The problem with `@belapsed` is that for OptimalControl when I run `@belapsed (sol = OC.solve(model,...))` , I don't have access to sol.
I can still run `solve` outside `@belapsed` to access the solutions, but it'll be as if I precompiled my functions.
Should I use  `Benchmarktools.jl`?

**Comment by 0Yassine0** [comment]
Unless there are some other modifications I can add for the Callbacks benchmark, should we close this issue?
