### ISSUE TITLE
Vectorial initial guess without the final time

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#23]
Il est possible maintenant de fournir un vecteur de vecteurs pour l'initialisation. Voir ce tutoriel : https://control-toolbox.org/docs/optimalcontrol/stable/tutorial-initial-guess.html#Vector-initial-guess-(interpolated)

_Originally posted by @ocots in https://github.com/0Yassine0/COTS.jl/issues/9#issuecomment-2222843668_
            
 
@frapac @ocots @jbcaillau          
I was looking into comparing of the initial guess between `JuMP` and `OC` and I realised that when have a simple constant value the two nlp models have the same x0, so that's a good news. However, when I use the new update in a free final time model, I used the initial guess as a final time :
  ```julia
  x0xinit[ [....] for k=0:n]
  time_vec = LinRange(0.0,tf_0,n+1) 
  init = (time= time_vec, state = xinit, control = c0 ,variable= tf_0);
``` 
,and that doesn't give the same results as JuMP.
Am I misusing the function ?

**Comment by jbcaillau** [comment]
@0Yassine0 indeed, @PierreMartinon is the one to ask. One thing: as far as I remember, `time_grid` is internally normalised to $[0,1]$, so you can as well pass `0:n`.

**Comment by PierreMartinon** [comment]
Yes, the grid is normalized !
