### ISSUE TITLE
Instance space_shuttle_reentry

### ISSUE THREAD

**Issue by frapac** [0Yassine0/COTS.jl#5]
Nous pouvons trouver le tutoriel suivant dans JuMP: https://jump.dev/JuMP.jl/stable/tutorials/nonlinear/space_shuttle_reentry_trajectory/

Je pense qu'il serait bien de pouvoir implémenter cet exemple dans OptimalControl.jl, car il est assez complet. 

J'observe que cette instance est dégénérée et pose problème pour le solveur nonlinéaire (nous convergeons vers des solutions différentes si nous changeons de solveur). Il serait bien d'essayer d'identifier la source de la dégénerescence dans le modèle.

**Comment by 0Yassine0** [comment]
Pour ce problème je rencontre quelques soucis déjà en testant les deux différentes méthodes d'intégration : rectangulaire et trapézoïdale (https://github.com/0Yassine0/COTS.jl/blob/7beebc20fea5789ceb050aed40a66cf7e262cc76/TestProblems/testSpaceShuttle.ipynb). Les deux versions trouvent deux résultats bien éloignés ( 34.18° contre 89° ) et la méthode trapézoïdale nécessite beaucoup plus de temps pour s'exécuter ( ~10 min avec Ipopt)

**Comment by 0Yassine0** [comment]
En travaillant avec la méthode rectangulaire, https://github.com/0Yassine0/COTS.jl/blob/7beebc20fea5789ceb050aed40a66cf7e262cc76/TestProblems/testSpaceShuttle.ipynb:
* J'ai comparé les différents solveurs linéaires avec Ipopt pour voir s'il donnent les mêmes résultats et c'était le cas.
* J'évalue dans un premier temps les résultats de MadNLP par rapport à celle de Ipopt. je pense que le problème vient du solveur linéaire utilisé par défaut dans MadNLP ( UmfpackSolver ). En choisissant le solveur linéaire MUMPS ou HSL_57 j'obtiens les mêmes résultats.

**Comment by frapac** [comment]
Ces résultats sont intéressant. Visiblement la méthode des trapèzes met bien plus à contribution le solveur linéaire que la méthode des rectangles (schéma d'intégration implicite versus explicite). Je pense qu'on peut attendre qu'elle soit plus lente, mais de la à passer à 10mn de temps de résolution ? 

Je confirme que MadNLP utilise Umfpack par défaut. Il faut faire en sorte d'utiliser HSL ma27 ou ma57, comme tu l'as vu. Je suis rassuré que MadNLP renvoie bien les meme résultats. En combien d'itérations converge MadNLP ? 

Dernière question : as-tu pu tester la formulation du problème space_shuttle_reentry avec OptimalControl.jl?

**Comment by 0Yassine0** [comment]
* Oui, mais ce que je trouve bizarre c'est que les deux méthodes donnent deux trajectoires différentes et les résultats ne sont pas égaux. Normalement la méthode des trapèzes est plus précise mais elle n'est pas censée trouver des résultats bien différentes à celle des rectangles.

* MadNLP converge en `618` itérations avec ma57. J'ai rajouté un petit tableau de comparaison à la fin du fichier : https://github.com/0Yassine0/COTS.jl/blob/bc8b2f32c8d09a5f740da77960e1ef7458abd5e6/TestProblems/SpaceShuttleIssue.ipynb#L296

* J'ai testé une fois la formulation du problème space_shuttle_reentry avec OptimalControl.jl (https://github.com/0Yassine0/COTS.jl/blob/bc8b2f32c8d09a5f740da77960e1ef7458abd5e6/Problems/OptimalControl/space_Shuttle_OC.jl) mais ça pris trop de temps (>30mn) , et là ou je me suis rendu compte que la méthode des trapèzes ( utilisé par OC) peux causer des problèmes à la résolution. Mais je travaillerai plus sur cette partie

**Comment by 0Yassine0** [comment]
Pour la méthode des trapèzes, j'ai réussi à trouver des résultats meilleurs.

Dans le code proposé par JuMP, ils utilisent la fonction `Fix` (https://jump.dev/JuMP.jl/stable/api/JuMP/#fix) pour fixer les conditions initiales et finales. Cette fonction supprime les contraintes déjà définies. Mais je ne sais pas encore pourquoi ça cause un problème que pour la méthode des trapèzes.

J'ai changé cette partie par `@constraints` et ça me donne des résultats plus proches de celle avec la méthode des rectangles.

**Comment by frapac** [comment]
C'est noté. Les résultats sont dépendants de la formulation que nous utilisons : souvent en controle optimale, juste changer l'ordre de déclaration des variables donne une convergence différente dans le solveur. 

Je ne suis pas étonné que `fix` pose un problème ici. Le notebook est-il à jour ? Je suis curieux de voir les résultats.

**Comment by 0Yassine0** [comment]
Oui, c'est bien à jour. Mais ce qui me perturbe maintenant vu que la méthode des trapèzes ne cause pas un vrai problème à la résolution c'est qu'empêche la résolution avec OC à trouver une solution.

**Comment by frapac** [comment]
Merci. Les résultats sont bien mieux maintenant. Bien vu pour `fix`. 

Peut-on changer l'intégrateur dans OC? Par exemple utiliser un pas d'Euler explicite pour la collocation.

**Comment by 0Yassine0** [comment]
C'était ma question à Mr. @ocots. Est-ce que j'ai des options pour choisir. Et aussi ça sera bien de pouvoir tester la méthode des rectangles avec OC pour comparer ces résultats avec celles de JuMP.

**Comment by ocots** [comment]
Pour le moment il n'y a que les trapèzes qui sont présents mais la discussion est intéressante.

@jbcaillau Résultats intéressants.

**Comment by ocots** [comment]
@0Yassine0 Pourrais-tu faire une autre issue pointant l'exemple qui ne marche pas avec `OptimalControl` et qui fonctionne avec `JuMP` ? Pourrais-tu créer un fichier juste pour ça pour qu'il soit archivé ?
