### ISSUE TITLE
Bonnes pratiques sur le benchmark

### ISSUE THREAD

**Issue by ocots** [0Yassine0/COTS.jl#6]
Je note ici les bonnes pratiques pour le benchmark à compléter.

- Utiliser le même itéré initial pour toutes les expérimentations que l'on compare entre-elles
- Passer les mêmes les options pour les solveurs quand c'est possible. Par exemple, avec `OptimalControl` l'options `mu_strategy` est fixée à `adaptive` par défaut pour la résolution via `Ipopt`. Il faut donner la même option à `JuMP` si l'on résout par `Ipopt`.

**Comment by ocots** [comment]
Tu peux jeter un oeil à ce package : https://github.com/KristofferC/TimerOutputs.jl

**Comment by ocots** [comment]
Pour récupérer les différents temps avec `Ipopt`, voir la discussion suivante : https://github.com/control-toolbox/CTDirect.jl/discussions/111#discussioncomment-9799370

**Comment by 0Yassine0** [comment]
* Pour le package [TimerOutputs.jl](https://github.com/KristofferC/TimerOutputs.jl) je ne suis pas sûr que ça soit utile parce que je n'ai pas la main sur les sous-parties de code dans `optimize!()` par exemple donc je ne pense pas que je peux afficher les différents temps passés dans les différentes parties d'un solveur. BenchmarkTools.jl renvoi le temps total ce qui bien déjà.

* Pour récupérer  différents temps avec Ipopt je n'ai pas trouvé une fonction qui renvoie les temps en forme `Float64` mais en renvoyant les résultats dans un fichier grâce aux options de Ipopt et en parsant ce fichier j'ai pu récupérer au moins le temps passé dans le solveur Ipopt.

> Dans mon dernier commit j'ai utilisé tout ce que j'ai dit ( voir [/Benchmark/GoddadModeles.ipynb](url))

**Comment by ocots** [comment]
@0Yassine0 tu peux essayer ça : https://github.com/control-toolbox/CTDirect.jl/discussions/111#discussioncomment-9909078

**Comment by ocots** [comment]
Je pense que l'on peut fermer cette issue.
