### ISSUE TITLE
OC.jl results for Space Shuttle Reentry problem

### ISSUE THREAD

**Issue by 0Yassine0** [0Yassine0/COTS.jl#8]
@ocots Dans le [notebook](https://github.com/0Yassine0/COTS.jl/blob/main/TestProblems/testSpaceShuttleOC.ipynb) , j'affiche les resultats du probleme Space Shuttle Reentry avec `OptimalControl.jl`. Le problème est modélisé [ici](https://github.com/0Yassine0/COTS.jl/blob/1b432ba1cb669a329c1631967af5d9ea0e5283c4/Problems/OptimalControl/space_Shuttle_OC.jl).
J'ai rajouté à la fin du notebook les résultats donnés par JuMP pour comparer les deux résultats. 
J'essayerai d'améliorer le notebook pour qu'il soit archivé.

**Comment by jbcaillau** [comment]
salut @0Yassine0 (copie @ocots et @PierreMartinon) ; pour la comparaison avec `JuMP` : une contrainte du [type](https://github.com/0Yassine0/COTS.jl/blob/a196052c56a706fc340c65691cbad8d87cb5f7f3/Problems/OptimalControl/space_Shuttle_OC.jl#L95C52-L95C56)

```julia
deg2rad(-89) ≤ θ(t) ≤ deg2rad(89),      (θ_con)
``` 

est bien parsée en une `:state_range` constraint, voir [ici](https://github.com/control-toolbox/CTBase.jl/blob/d2aa9b48ef2a799e921d7fc1e49276ef8b2c64ce/src/ctparser_utils.jl#L358)

![IMG_3279](https://github.com/0Yassine0/COTS.jl/assets/62183989/bc2335a9-3280-44f1-bf7c-150195c7c4c3)

et va donner une contrainte de boîte après traitement par `CTBase.nlp_constraints!` et `CTDirect.jl`.

**Comment by ocots** [comment]
Pourrait-on avoir le nombre de contraintes de boite et non linéaire avec `JuMP` et `OptimalControl`.

**Comment by 0Yassine0** [comment]
@ocots. J'ai les deux nombres dans [testSpaceShuttleOC](https://github.com/0Yassine0/COTS.jl/blob/1a4a3678b6fbc66db331cad8fd640b9cab093d9e/TestProblems/testSpaceShuttleOC.ipynb#L2296). Mais le nombre des contraintes de boite dépend du `grid_size` pour `OptimalControl` : voir [ici](https://github.com/0Yassine0/COTS.jl/blob/1a4a3678b6fbc66db331cad8fd640b9cab093d9e/TestProblems/testSpaceShuttleOC.ipynb#L816). Ce nombre est de 503 pour `JuMP`, ce qui ne marche pas pour `OptimalControl` ( la limite est 502 ) .

**Comment by ocots** [comment]
Il faut alors changer le `grid_size` de `JuMP` pour comparer. Tu peux mettre une grille de 100 points pour chacun.

**Comment by ocots** [comment]
@PierreMartinon @jbcaillau En fait, nous avons un problème avec l'init. Il semblerait que l'on fournisse l'initialisation par défaut à `ipopt` alors que @0Yassine0 à écrit ça : 

```julia

x_s = [h_s, ϕ_s, θ_s, v_s, γ_s, ψ_s, α_s, β_s]
x_t = [h_t, ϕ_s, θ_s, v_t, γ_t, ψ_s, α_s, β_s]
interp_linear = Interpolations.LinearInterpolation([1, n], [x_s, x_t])
initial_guess = mapreduce(transpose, vcat, interp_linear.(1:n))


xinit = initial_guess[:,1:6]
uinit = initial_guess[:,7:8]

init = (x_init = xinit,u_init = uinit)
```

Il semblerait donc qu'il y ait un bug pour l'initial guess.

**Comment by ocots** [comment]
On le voit bien ici : 

```bash
Method = (:direct, :adnlp, :ipopt)
This is Ipopt version 3.14.14, running with linear solver ma57.

Number of nonzeros in equality constraint Jacobian...:     6009
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:     2424

Total number of variables............................:      808
                     variables with only lower bounds:      202
                variables with lower and upper bounds:      404
                     variables with only upper bounds:        0
Total number of equality constraints.................:      609
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0 -1.0000000e-01 2.01e+03 1.11e+00   0.0 0.00e+00    -  0.00e+00 0.00e+00   0
```

On voit qu'à la première itération, l'objectif vaut -0.1 or ça devrait être 0. Nous on initialise par défaut à 0.1 mais ici nous avons un problème de max. C'est un problème de Mayer et donc l'objectif c'est juste la variable theta au temps final qui est initialisée à 0 en vrai.

**Comment by jbcaillau** [comment]
Voir aussi cette [discussion](https://discourse.julialang.org/t/jump-constraint-with-a-huge-expression/108456) sur l'utilisation de JuMP avec de "grandes expressions". Les cas traités sont possiblement intéressants (Dubins...)

**Comment by ocots** [comment]
Il y a une question pour nous : https://discourse.julialang.org/t/jump-constraint-with-a-huge-expression/108456/10

**Comment by jbcaillau** [comment]
> Il y a une question pour nous : https://discourse.julialang.org/t/jump-constraint-with-a-huge-expression/108456/10

Déjà répondu en [février dernier](https://discourse.julialang.org/t/jump-constraint-with-a-huge-expression/108456/24?u=jbcaillau), je vous avais fait suivre l'échange dans les discussions de l'organisation.

**Comment by PierreMartinon** [comment]
> On le voit bien ici :
> 
> ```shell
> Method = (:direct, :adnlp, :ipopt)
> This is Ipopt version 3.14.14, running with linear solver ma57.
> 
> Number of nonzeros in equality constraint Jacobian...:     6009
> Number of nonzeros in inequality constraint Jacobian.:        0
> Number of nonzeros in Lagrangian Hessian.............:     2424
> 
> Total number of variables............................:      808
>                      variables with only lower bounds:      202
>                 variables with lower and upper bounds:      404
>                      variables with only upper bounds:        0
> Total number of equality constraints.................:      609
> Total number of inequality constraints...............:        0
>         inequality constraints with only lower bounds:        0
>    inequality constraints with lower and upper bounds:        0
>         inequality constraints with only upper bounds:        0
> 
> iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
>    0 -1.0000000e-01 2.01e+03 1.11e+00   0.0 0.00e+00    -  0.00e+00 0.00e+00   0
> ```
> 
> On voit qu'à la première itération, l'objectif vaut -0.1 or ça devrait être 0. Nous on initialise par défaut à 0.1 mais ici nous avons un problème de max. C'est un problème de Mayer et donc l'objectif c'est juste la variable theta au temps final qui est initialisée à 0 en vrai.


Je regarde ca et je vous dis !

**Comment by PierreMartinon** [comment]
> @PierreMartinon @jbcaillau En fait, nous avons un problème avec l'init. Il semblerait que l'on fournisse l'initialisation par défaut à `ipopt` alors que @0Yassine0 à écrit ça :
> 
> ```julia
> x_s = [h_s, ϕ_s, θ_s, v_s, γ_s, ψ_s, α_s, β_s]
> x_t = [h_t, ϕ_s, θ_s, v_t, γ_t, ψ_s, α_s, β_s]
> interp_linear = Interpolations.LinearInterpolation([1, n], [x_s, x_t])
> initial_guess = mapreduce(transpose, vcat, interp_linear.(1:n))
> 
> 
> xinit = initial_guess[:,1:6]
> uinit = initial_guess[:,7:8]
> 
> init = (x_init = xinit,u_init = uinit)
> ```
> 
> Il semblerait donc qu'il y ait un bug pour l'initial guess.

En effet, probleme de syntaxe:
- les noms des arguments sont maintenant 'state' et 'control' au lieu de x_init et u_init
- 

On a peut-etre de la mise a jour a faire sur la doc.
Un exemple de test https://github.com/control-toolbox/CTDirect.jl/blob/main/test/test_initial_guess.jl

On pourrait sans doute ameliorer l'init pour accepter des matrices (quitte a reinterpoler si les dimensions ne collent pas). Et aussi afficher un message si les arguments ne sont pas reconnus, ce qui en pratique conduit a l'initialisation par defaut a 0.1

**Comment by ocots** [comment]
Oui il faut mettre à jour la doc. Finalement, pour ce problème on a le même nombre de contraintes de chaque type entre `JuMP` et `OptimalControl`. Le souci venait de l'init. 

On peut fermer l'issue je pense.

**Comment by 0Yassine0** [comment]
> Oui il faut mettre à jour la doc. Finalement, pour ce problème on a le même nombre de contraintes de chaque type entre `JuMP` et `OptimalControl`. Le souci venait de l'init.
> 
> On peut fermer l'issue je pense.

@ocots @frapac @PierreMartinon 
Je suis désolé, mais le problème du space shuttle n'est toujours pas solvable avec `OptimalControl`. Je n'ai plus de souci avec l'`initial guess`, mais le problème ne converge plus. Dans le [notebook](https://github.com/0Yassine0/COTS.jl/blob/1b432ba1cb669a329c1631967af5d9ea0e5283c4/TestProblems/testSpaceShuttleOC.ipynb), je l'ai limité à 500 itérations pour que l'on puisse voir des résultats, mais le problème ne converge pas non plus avec les 3000 itérations par défaut.

**Comment by ocots** [comment]
Merci pour l'info. On est d'accord que le lien est toujours valide. Sinon peux-tu le remettre.
